[theme]
primaryColor = "#ff0000"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1d29"
textColor = "#ffffff"
font = "sans serif"
base = "dark"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 